# Generated by Django 2.2 on 2021-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name="Tag's name")),
                ('user_pk', models.PositiveIntegerField(default=0, verbose_name='user_pk')),
                ('user_from_pk', models.PositiveIntegerField(default=0, verbose_name='user_from_pk')),
            ],
        ),
    ]
