# Generated by Django 2.2 on 2021-06-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('YM', 'Yandex Music'), ('SP', 'Spotify'), ('VK', 'VK')], default='YM', max_length=2)),
                ('idYandex', models.PositiveIntegerField(verbose_name='YandexMusicID')),
                ('idDiscogs', models.PositiveIntegerField(verbose_name='DiscogsID')),
                ('idDiscogsSecondary', models.PositiveIntegerField(null=True, verbose_name='DiscogsSecondaryID')),
                ('name', models.CharField(max_length=128, verbose_name="Album's name")),
                ('imageURL', models.CharField(default='', max_length=512, null=True, verbose_name='Image url')),
                ('cover', models.ImageField(blank=True, height_field=100, upload_to='', width_field=100)),
                ('year', models.PositiveIntegerField(default=0, verbose_name='year')),
                ('artists', models.ManyToManyField(blank=True, related_name='albums', to='mainapp.Artist', verbose_name='Artists')),
                ('genres', models.ManyToManyField(blank=True, related_name='genred_albums', to='mainapp.Genre')),
                ('labels', models.ManyToManyField(blank=True, related_name='labeled_albums', to='mainapp.Label')),
                ('styles', models.ManyToManyField(blank=True, related_name='styled_albums', to='mainapp.Style')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_albums', to='mainapp.Tag')),
            ],
        ),
    ]
