# Generated by Django 2.2 on 2021-06-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagShareRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from_pk', models.PositiveIntegerField(default=0, verbose_name='User from pk')),
                ('user_to_pk', models.PositiveIntegerField(default=0, verbose_name='User to pk')),
                ('tags', models.ManyToManyField(blank=True, related_name='requests', to='mainapp.Tag', verbose_name='tags')),
            ],
        ),
    ]
