# Generated by Django 2.2 on 2021-06-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_tagsharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='idSpotify',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Spotify id'),
        ),
        migrations.AddField(
            model_name='artist',
            name='idSpotify',
            field=models.CharField(blank=True, max_length=128, verbose_name='Spotify id'),
        ),
        migrations.AddField(
            model_name='artist',
            name='idYandexMusic',
            field=models.CharField(blank=True, max_length=128, verbose_name='Artist yandex music id'),
        ),
    ]
