# Generated by Django 2.2 on 2021-06-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210607_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='idSpotify',
            field=models.CharField(default='-1', max_length=1024, verbose_name='Spotify id'),
        ),
        migrations.AlterField(
            model_name='album',
            name='idYandex',
            field=models.PositiveIntegerField(default=0, verbose_name='YandexMusicID'),
        ),
    ]
