# Generated by Django 2.2 on 2021-06-07 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
