# Generated by Django 2.2 on 2021-06-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='friendRequests',
            field=models.ManyToManyField(blank=True, related_name='to_this_user', to='authapp.FriendRequest'),
        ),
    ]
