# Generated by Django 2.2 on 2021-06-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_siteuser_codesp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='emailYM',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='yandex Music email'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='passwordSP',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Spotify password'),
        ),
    ]
